spring:
  datasource:
    url: jdbc:mysql://172.21.0.4:3306/raydb_trade?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: raykite
    driver-class-name: com.mysql.cj.jdbc.Driver

process:
  processInstanceKey:
    projectConfirm: project_confirm