spring:
  datasource:
    url: jdbc:mysql://10.10.10.113:3306/raydb_trade?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Raykite_888!
    driver-class-name: com.mysql.cj.jdbc.Driver

process:
  processInstanceKey:
    projectConfirm: project_confirm