eureka:
  client:
    healthcheck:
        enabled: true
    serviceUrl:
        defaultZone: http://user:123456@172.17.207.24:8761/eureka
  instance:
      prefer-ip-address: true

spring:
  datasource:
    coupon: #coupons优惠券数据源
      url: jdbc:mysql://172.17.207.22:3306/bainuo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: gYG3tOqWa775
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxIdle: 20
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000